### PR TITLE
Release/6.3.0

### PR DESCRIPTION
**Pull request by fkonvick**
This is the (hopefully complete) collection of my changes to Gecode for 6.3.0.  I did not create a separate branch for each change but hopefully the changes are simple enough to review.

### CODE REVIEW

**Comment by ozgurakgun** [comment]
Hi @fkonvick - thanks for this.

I tried building this PR, but got an error (on macos, arm processor)

```
g++ -I. -I.. -Qunused-arguments -fno-rounding-math -ffinite-math-only -fno-math-errno -fno-strict-aliasing -O3 -fvisibility=hidden -ggdb -std=c++17 -pipe -Wno-unknown-pragmas -Wall -Wextra -fPIC -pthread -DNDEBUG   \
	 \
	-c -o gecode/flatzinc/flatzinc.o  ../gecode/flatzinc/flatzinc.cpp
g++ -I. -I.. -Qunused-arguments -fno-rounding-math -ffinite-math-only -fno-math-errno -fno-strict-aliasing -O3 -fvisibility=hidden -ggdb -std=c++17 -pipe -Wno-unknown-pragmas -Wall -Wextra -fPIC -pthread -DNDEBUG   \
	 \
	-c -o gecode/flatzinc/registry.o  ../gecode/flatzinc/registry.cpp
g++ -I. -I.. -Qunused-arguments -fno-rounding-math -ffinite-math-only -fno-math-errno -fno-strict-aliasing -O3 -fvisibility=hidden -ggdb -std=c++17 -pipe -Wno-unknown-pragmas -Wall -Wextra -fPIC -pthread -DNDEBUG   \
	 \
	-c -o gecode/flatzinc/branch.o  ../gecode/flatzinc/branch.cpp
cp ../gecode/flatzinc/parser.tab.cpp gecode/flatzinc/parser.tab.cpp
g++ -I. -I.. -Qunused-arguments -fno-rounding-math -ffinite-math-only -fno-math-errno -fno-strict-aliasing -O3 -fvisibility=hidden -ggdb -std=c++17 -pipe -Wno-unknown-pragmas -Wall -Wextra -fPIC -pthread -DNDEBUG   \
	 \
	-c -o gecode/flatzinc/parser.tab.o  gecode/flatzinc/parser.tab.cpp
gecode/flatzinc/parser.tab.cpp:526:10: fatal error: 'parser.tab.hpp' file not found
#include "parser.tab.hpp"
         ^~~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [gecode/flatzinc/parser.tab.o] Error 1
```

I remember getting this error in the past but I am not sure what the fix was, sorry.

**Comment by fkonvick** [comment]
Thanks for trying.  I think that this might be unrelated to my changes - could you successfully build the 6.3.0 release branch as is, without the PR applied?
I would think that parser.tab.hpp is a product of some Flex/Bison build steps, so perhaps your build configuration is missing these, or Perl.

**Comment by ozgurakgun** [comment]
I think you are right.

**Comment by fkonvick** [comment]
@zayenz Thanks.  I got a notification saying "Gecode release/6.3.0" and I thought wow :) but then I realized it was just a merge.  If there's anything I can do to help, please let me know!

**Comment by zayenz** [comment]
Yep, the branch name merged was a bit conspicuous. 

Trying to get everything squared up now, and will check in on your build during next week.

**Pull request merged**
