### PR TITLE
Fix FlatZinc parser generation for Bison 3.7

### LINKED ISSUE #77: Build fails with Bison 3.7
Debian updated to Bison 3.7 and building Gecode 6.2.0 fails with it. The gecode/flatzinc/parser.tab.cpp file it generates has an `#include "parser.tab.hpp"` directive in it and since make renames parser.tab.hpp as parser.tab.hh, that fails.

I fixed  it for Debian by adding this to the gecode/flatzinc/parser.tab.cpp target in Makefile.in:
```
sed -i 's/^#include "parser.tab.hpp"/#include "parser.tab.hh"/' gecode/flatzinc/parser.tab.cpp
```

### PR DESCRIPTION
**Pull request by Dekker1**
This moves the header file generated by Bison to `gecode/flatzinc/parser.tab.hpp`. The usage of `parser.tab.hpp` is the default location used by Bison. Since Bison 3.7 the header file is no longer contained in the generated implementation file and will instead have `#include "parser.tab.hpp"`. The location change will allow parser generation with Bison 3.7 while keeping compatibility with older versions of Bison.

(The alternative would have been to set the header location using the dedicated Bison option:
```%define api.header.include {<gecode/flatzinc/parser.tab.hh>}```
This would however break any compatibility with any Bison version before 3.4)

Fixes #77

### CODE REVIEW

**Comment by zayenz** [comment]
Thanks for fixing this issue. Unfortunately, the Travis builds did not go through yet (https://travis-ci.org/github/Gecode/gecode/jobs/722959827)

    make[1]: *** No rule to make target 'gecode/flatzinc/parser.tab.hh', needed by 'gecode/flatzinc/parser.tab.o'.  Stop.

I need to check why before I merge it in.

**Comment by Dekker1** [comment]
I thought I had changed all relevant places. I'm not really sure how the autoconfigure fully works so maybe I might have missing something.

The only mention I still see that I'm not sure about is `Makefile.dep`. I'm not sure if that is a generated file or if the filename should be changed there as well.
If Travis uses caching for the configure step, then that would also cause the issue.

**Comment by zayenz** [comment]
Might be some caching on Travis. 

Apart from that, Makefile.dep should be regenerated, which is normally done using `make depend`. I saw that you added the change in the latest push. However, running `make depend` in your branch errors with 

    ...
    tenpenki_1.cpp test/flatzinc/tenpenki_2.cpp test/flatzinc/tenpenki_3.cpp test/flatzinc/tenpenki_4.cpp test/flatzinc/tenpenki_5.cpp test/flatzinc/tenpenki_6.cpp test/flatzinc/warehouses.cpp test/flatzinc/warehouses_small.cpp test/flatzinc/wolf_goat_cabbage.cpp test/flatzinc/zebra.cpp test/flatzinc/magicsq_3.cpp test/flatzinc/magicsq_4.cpp test/flatzinc/magicsq_5.cpp test/flatzinc/oss.cpp test/flatzinc/steiner_triples.cpp test/flatzinc/timetabling.cpp test/flatzinc/trucking.cpp > Makefile.dep
    File missing: ./parser.tab.hpp
    make: *** [depend] Error 2

I am unsure why this error happens though. Does it happen for you also?

**Comment by Dekker1** [comment]
Ah, that explains how the file was meant to be changed (although I'm still unsure what is is used for).

I'm having the same issue when running `make depend`. I must have broken something. I'll see if I can find out what went wrong

**Comment by zayenz** [comment]
Travis build for this PR is green now: https://travis-ci.org/github/Gecode/gecode/builds/722977239

Makefile.dep is intended to record all the dependency information in the project between files. While not the most elegant and automatic of solutions, it generally works well and relies on the somewhat regular structure of the project to use a simple solution.

**Comment by Dekker1** [comment]
I found the problem. The newly generated parser.tab.cpp has a relative include to `"parser.tab.hpp"`. The `makedeps` perl assumes that this file would be located in the global directory instead of the same directory as the cpp file.

**Comment by Dekker1** [comment]
I've updated the perl script to handle quoted includes for files in the current directory. The perl script now (on my machine) generates the same `Makefile.dep` as the one that was created by my manual changes.

**Comment by zayenz** [comment]
Great work @Dekker1! The changes look good to me.

Just for extra security, I'll wait for the final Travis build before merging.

**Pull request merged**
