### PR TITLE
Use single option to activate cp-profiler

### PR DESCRIPTION
**Pull request by cyderize**
Uses the new combined `-cpprofiler` standard flag. Always sends info when profiling.

### CODE REVIEW

**Comment by zayenz** [comment]
Thanks for this change. Since you added the changelog entry to the 6.3.0 tag, I'm thinking that you would like us to add it to the release/6.3.0 branch as well?

**Comment by zayenz** [comment]
I will merge this and also add it to `release/6.3.0`.

**Comment by cyderize** [comment]
Sorry, could you hold off for now, there's actually a small change I need to make to this first

**Comment by cyderize** [comment]
I'll re-open this when it's ready. Thanks

**Comment by zayenz** [comment]
Sure, no problem

**Pull request closed without merging**
